import { Inter } from "next/font/google";
import "../styles/main.css";
import Navbar from "../component/Navbar";
import { GetStatesGlobally } from "../Hooks/globalStates";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce Website",
  description: "Generated by sumeria mahi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GetStatesGlobally>
          <Navbar />
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </GetStatesGlobally>
      </body>
    </html>
  );
}
